name: Build

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    if: github.repository == 'iOSRealRun-cli/iOSRealRun-cli'
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: ${{ matrix.arch }}
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true

      - name: Copy Files (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir output
          mkdir output/libimobiledevice
          cp build/*.exe output/
          cp config.yaml output/
          cp *route.txt output/
          cp -r DeveloperDiskImage output/
          cp -r libimobiledevice/win output/libimobiledevice
        
      - name: Copy Files (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir output
          mkdir output/libimobiledevice
          cp build/*.bin output/
          chmod +x output/*.bin
          cp config.yaml output/
          cp *route.txt output/
          cp -r DeveloperDiskImage output/
          cp -r libimobiledevice/linux output/libimobiledevice
      
      - name: Copy Files (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir output
          mkdir output/libimobiledevice
          cp build/*.bin output/
          cp config.yaml output/
          cp *route.txt output/
          cp main.command output/
          cp -r DeveloperDiskImage output/
          cp -r libimobiledevice/darwin output/libimobiledevice

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iOSRealRun-cli-${{ runner.os }}-${{ matrix.arch }}
          path: |
            output/
